// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace banco.Models;

public partial class Cliente
{
    public int Id { get; set; }

    public char RazonSocial { get; set; }

    public int Cuil { get; set; }

    public DateOnly? Alta { get; set; }

    public int DireccionId { get; set; }

    public virtual ICollection<ClienteXcuentum> ClienteXcuenta { get; set; } = new List<ClienteXcuentum>();

    public virtual Direccion Direccion { get; set; }
}