// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace banco.Models;

public partial class ClienteXcuentum
{
    public int Id { get; set; }

    public DateOnly Alta { get; set; }

    public char Rol { get; set; }

    public int ClienteId { get; set; }

    public int CuentaId { get; set; }

    public virtual Cliente Cliente { get; set; }

    public virtual Cuentum Cuenta { get; set; }
}