// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace banco.Models;

public partial class Direccion
{
    public int Id { get; set; }

    public char Calle { get; set; }

    public char? Departamento { get; set; }

    public char Numero { get; set; }

    public int LocalidadId { get; set; }

    public virtual ICollection<Cliente> Clientes { get; set; } = new List<Cliente>();

    public virtual Localidad Localidad { get; set; }
}