// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace banco.Models;

public partial class Pai
{
    public int Id { get; set; }

    public char Nombre { get; set; }

    public virtual ICollection<Localidad> Localidads { get; set; } = new List<Localidad>();
}