// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace banco.Models;

public partial class Transaccion
{
    public int Id { get; set; }

    public decimal Monto { get; set; }

    public long? NumeroOperacion { get; set; }

    public DateOnly? Fecha { get; set; }

    public int CuentaOrigenId { get; set; }

    public int CuentaDestinoId { get; set; }

    public int TipoTransaccionId { get; set; }

    public virtual Cuentum CuentaDestino { get; set; }

    public virtual Cuentum CuentaOrigen { get; set; }

    public virtual TipoTransaccion TipoTransaccion { get; set; }
}